- name: Validate variables for deploy_config.yml task
  ansible.builtin.assert:
    that:
      - lsyncd_config_base is defined
      - lsyncd_config_file is defined
      - lsyncd_log_file is defined
      - lsyncd_status_file is defined
      - lsyncd_status_interval is defined
      - lsyncd_nodaemon is defined
      - lsyncd_insist is defined
      - lsyncd_max_processes is defined
      - lsyncd_inotify_mode is defined
      - lsyncd_config is defined

- name: Validate lsyncd_config structure
  ansible.builtin.assert:
    that:
      - lsyncd_config.values() | map('type_debug') | select('ne', 'list') | list | length == 0
    fail_msg: "Each lsyncd_config entry must be a list of remote target dicts"

- name: Ensure lsyncd_config_base exists
  ansible.builtin.file:
    name: "{{ lsyncd_config_base }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy config
  ansible.builtin.template:
    src: lsyncd.conf.lua.j2
    dest: "{{ lsyncd_config_file }}"
    owner: root
    group: root
    mode: '0644'
